version: 1
update_configs:
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "weekly"
    default_reviewers:
      - "davemcorwin"
      - "amirbey"
    default_assignees:
      - "davemcorwin"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"      
